#!/bin/bash

echo "---------数组--------------"

#初始化一个数组
array_var=(1 3 4 5 6);
#利用索引赋值
array_var[0]="test1";
array_var[1]="test2";
array_var[2]="test3";

#打印指定索引的值
echo ${array_var[0]};

index=3;
echo ${array_var[$index]};


#以清单的方式,打印数组中所有的值
echo ${array_var[*]};

echo "数组的索引列表:" ${!array_var[*]}; #数组的索引列表   加!


echo ${array_var[@]};

echo "数组长度:" ${#array_var[*]};




echo "----------关联数组------ bash4.0 版本才被引入 -----------"

declare -a like_array;
like_array=([index1]="value at index1 " [index2]="value at index2");
echo ${like_array[*]};





